config/routes.rb
Netdev::Application.routes.draw do

  get '/news/rss'
  
  match "/articles", :to => "pages#articles"
  match "/about", :to => "pages#about"

  root :to => "pages#home"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title
  
  cattr_reader :per_page
  @@per_page = 6

  has_many :comments

  validates :title, :presence => true,
                    :length => { :minimum => 4}
  validates :content, :presence => true
  
  default_scope :order => 'articles.created_at DESC'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :name, :email, :content
  
  belongs_to :article
  
  validates :name, :presence => true,
                   :length => { :within => 5..10 }
  validates :content, :presence => true
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :title, :content
  
  cattr_reader :per_page
  @@per_page = 10
  
  validates :title, :presence => true
  validates :content, :presence => true
  
  default_scope :order => 'news.created_at DESC'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def rss
    @news = New.find(:all, :order => "id DESC", :limit => 10)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    @news = New.paginate(:page => params[:page])
  end

  def articles
    @title = "Articles"
    @articles = Article.paginate(:page => params[:page])
  end

  def about
    @title = "About"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li>Copyright © 2011</li>
			<li><%= link_to "About Me", about_path %></li>
			<li><%= link_to image_tag("rss.png", :size => "18x18"), "news/rss.rxml" %>
			<li><%= link_to image_tag("mail.png", :size => "18x18"), "mailto:nvanderauwera@gmail.com?subject=Netdev - Contact" %>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav id="tab">
		<%#tabs_tag do |tab| %>
			<%# tab.home "Home", root_path %>
			<%# tab.articles "Articles", articles_path %>
			<%# tab.about "About", about_path %>
		<%#end %>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Netdev | <%= @title %></title>
  	<%= javascript_include_tag :defaults %>
  	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= auto_discovery_link_tag(:rss, {:controller => "news", :action => "rss"}) %>
</head>
<body>
	<div id="container">
		<%= render "layouts/header" %>
		<section id="page">
			<nav id="menu">
				Ceci contient le menu
			</nav>
			<div id="content">
				<section class="title">
					<h1><%= @title %></h1>
				</section>
				<%= yield %>
			</div>
			<div class="clear"></div>
		</section>
		<%= render "layouts/footer" %>
	</div>
</body>
</html>

app/views/news/_new.html.erb
<article class="new">
	<h3><%= new.title %></h3>
	<p><%= new.content %></p>
	<span class="timestamp">
			Posted <%= time_ago_in_words(new.created_at) %> ago
	</span>
</article>

app/views/pages/home.html.erb
<%= render @news %>
<section class="pagination_div">
	<%= will_paginate @news, :inner_window => 2 %>
	<p><%= page_entries_info @news %></p>
	<div class="clear"></div>
</section>